logging:
  level:
    org:
      springframework:
         security: DEBUG

org:
  springframework:
    web:
      cors: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password

security:
  oauth2:
    client:
      clientId: <client_id>
      clientSecret: <secret>
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
        tokenInfoUri: https://www.googleapis.com/userinfo/me

